import { signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import { magic } from "../lib/magic";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { data: session } = useSession();

  const logout = async () => {
    await magic.user.logout();
    await signOut();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App using Magic and Next-Auth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="mb-4 text-lg font-semibold">
          Email: {session.user.email}
        </div>
        <button
          type="button"
          className="bg-green-700 hover:bg-green-500 text-white font-semibold py-2 px-4 rounded"
          onClick={logout}
        >
          Sign Out
        </button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

Home.auth = true;
